config/routes.rb
Rails.application.routes.draw do
  resources :events, only: %i[new create show edit update destroy] do
    resources :tickets, only: %i[new create destroy]
  end

  resource :retirements, only: %i[new create]

  #get 'welcome/index'
  root "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/auth/:provider/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "status" => 'status#index', defaults: { format: 'json' }

  match "*path" => "application#error404", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  has_many :tickets, dependent: :destroy
  belongs_to :owner, class_name: "User"

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at
  validates :image, content_type: [:png, :jpg, :jpeg], size: { less_than_or_equal_to: 10.megabytes }, dimension: { width: { max: 2000 }, height: { max: 2000 } }

  attr_accessor :remove_image
  before_save :remove_image_if_user_accept

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, "should be before end")
    end
  end

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: "Event", foreign_key: "owner_id", dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event # https://railsguides.jp/association_basics.html

  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now

    if created_events.where(":now < end_at", now: now).exists?
      errors[:base] << "Non-ended public event exists."
    end

    if participating_events.where(":now < end_at", now: now).exists?
      errors[:base] << "Non-ended event you participate exists."
    end

    throw(:abort) unless errors.empty? # https://qiita.com/___dera/items/6a73e84a183a706e4d39
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404

  private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: "Please Login."
  end

  def error404(_)
    render "error404", status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join("\n")
    render "error500", status: 500, formats: [:html]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: :show

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: "Event created."
    end
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Update successfully."
    end
  end

  # By using the `destroy!` method instead of the `destroy` method, RecordNotDestroyed will be raised when the deletion is aborted by a hook method called at the time of deletion.
  # `destroy` メソッドではなく `destroy!` メソッドを利用することで、削除時に呼ばれるフックメソッドで削除を中断するなどした場合に RecordNotDestroyed を raise させる。
  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: "Event deletion completed."
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :image, :remove_image, :content, :start_at, :end_at
    )
  end
end

app/controllers/retirements_controller.rb
class RetirementsController < ApplicationController
  def new
  end

  def create
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: "Retirement completed"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authenticate, only: :create

  def create
    user = User.find_or_create_from_auth_hash!(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, notice: "Logged-in successfully."
  end

  def destroy
    reset_session # https://railsdoc.com/page/reset_session
    redirect_to root_path, notice: "Logged-out successfully."
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  skip_before_action :authenticate

  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    raise ActionController::RoutingError, "Accessed TicketsController#new in logged-in state"
  end

  def create
    event = Event.find(params[:event_id])
    @ticket = current_user.tickets.build do |t|
      t.event = event
      t.comment = params[:ticket][:comment]
    end
    if @ticket.save
      redirect_to event, notice: "You joined this Event."
    end
  end

  def destroy
    puts params
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: "Cancel your participation of this Event is completed."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
    @events = Event.page(params[:page]).per(10)
      .where("start_at > ?", Time.zone.now).order(:start_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_github(user)
    "https://github.com/#{user.name}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/retirements_helper.rb
module RetirementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_errors.html.erb
<div class="alert alert-danger">
  <ul class="mb-0">
    <% errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
</div>

app/views/application/error404.html.erb
The page specified not exist.

app/views/application/error500.html.erb
Internal server error

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

app/views/events/edit.html.erb
<% now = Time.zone.now %>
<h1 class="mt-2">Edit Event details</h1>
<%= form_with(model: @event, class: "form-horizontal") do |f| %>
  <div id="errors"></div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_at %>
    <div>
      <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_at %>
    <div>
      <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", row: 10 %>
  </div>
  <div class="form-group">
  <%= f.label :image %>
  <% if @event.image.attached? && @event.image.blob&.persisted? %>
    <%= image_tag(@event.image.variant(resize_to_fit: [200, 200]), class: "img-thumbnail d-block mb-3") %>
    <%= f.file_field :image, class: "form-control-file" %>
  <% end %>
  <% if @event.image.attached? && @event.image.blob&.persisted? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :remove_image %>
        Delete Image
      </label>
    </div>
  <% end %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/events/new.html.erb
<% now = Time.zone.now %>
<h1 class="mt-2">Create new Event</h1>
<%= form_with(model: @event, class: "form-horizontal") do |f| %>
  <div id="errors"></div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_at %>
    <div>
      <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_at %>
    <div>
      <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", row:10 %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control-file" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<h1 class="mt-3 mb-3">
  <%= @event.name %>
</h1>
<div class="row">
  <div class="col-8">
    <div class="card mb-2">
      <% if @event.image.attached? %>
        <%= image_tag @event.image, class: "card-img-top" %>
      <% end %>
      <h5 class="card-header">Event Content</h5>
      <div class="card-body">
        <p class="card-text">
          <%= @event.content %>
        </p>
      </div>
    </div>
    <div class="card mb-2">
      <h5 class="card-header">Start Date</h5>
      <div class="card-body">
        <p class="card-text">
          <%= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}" %>
        </p>
      </div>
    </div>
    <div class="card mb-2">
      <h5 class="card-header">Place</h5>
      <div class="card-body">
        <p class="card-text">
          <%= @event.place %>
        </p>
      </div>
    </div>
    <div class="card mb-2">
      <h5 class="card-header">Owner</h5>
      <div class="card-body">
        <% if @event.owner %>
          <%= link_to(url_for_github(@event.owner), class: "card-link") do %>
            <%= image_tag @event.owner.image_url, width: 50, height: 50 %>
            <%= "@#{@event.owner.name}" %>
          <% end %>
        <% else %>
          This user is retired.
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-4">
    <% if @event.created_by?(current_user) %>
      <%= link_to "Edit this Event", edit_event_path(@event), class: "btn btn-info btn-lg btn-block" %>
      <%= link_to "Delete this Event", event_path(@event), class: "btn btn-danger btn-lg btn-block", method: :delete, data: { confirm: "Are you sure to delete this event?" } %>
    <% end %>
    <% if @ticket %>
      <%= link_to "Cancel my participation", event_ticket_path(@event, @ticket), method: :delete, class: "btn btn-warning btn-lg btn-block" %>
    <% elsif logged_in? %>
      <button class="btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">Join this Event</button>
      <div class="modal fade" id="createTicket">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="dialogHeader">Comment</h4>
              <button class="close" type="button" data-dismiss="modal">&times;</button>
            </div>
            <%= form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f| %>
              <div class="modal-body">
                <div id="createTicketErrors"></div>
                <%= f.text_field :comment, class: "form-control" %>
              </div>
              <div class="modal-footer">
                <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
                <%= f.button "Submit", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to "Join this Event", new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block" %>
    <% end %>
    <hr/>
    <div class="card mb-2">
      <h5 class="card-header">Participants</h5>
      <ul class="list-group list-group-flush">
        <% @tickets.each do |ticket| %>
          <li class="list-group-item">
            <% if ticket.user %>
              <%= link_to(url_for_github(ticket.user), class: "card-link") do %>
                <%= image_tag ticket.user.image_url, width: 20, height: 20 %>
                <%= "@#{ticket.user.name}" %>
              <% end %>
              <%= ticket.comment %>
            <% else %>
              This user is retired.
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <title>AwesomeEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <header class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <%= link_to "AwesomeEvents", root_path, class: "navbar-brand mr-auto" %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Create new Event", new_event_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item"></li>
            <%= link_to "Retirement", new_retirements_path, class: "nav-link" %>
            <li class="nav-item"></li>
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login via GitHub", "/auth/github", class: "nav-link", method: :post %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    <div class="container">
      <% if flash.notice %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <% if flash.alert  %>
        <div class="alert alert-danger">
          <%= flash.alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/retirements/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @current_user.errors) %>"

app/views/retirements/new.html.erb
<h1 class="mt-3">Confirm retirement</h1>
<div id="errors"></div>
<p>If you complete retirement, all data related you are deleted.</p>
<p>But, if you match below conditions, you can not complete retirement.</p>
<ul>
  <li>
    If you have non-ended public event
  </li>
  <li>
    If you join to non-ended event
  </li>
</ul>
<hr/>
<%= link_to "Retirement", retirements_path, method: :post, remote: true, class: "btn btn-danger", data: { confirm: "Are you sure to retirement?" } %>

app/views/tickets/create.js.erb
document.getElementById("createTicketErrors").innerHTML = "<%= j render("errors", errors: @ticket.errors) %>"

app/views/welcome/index.html.erb
<h1>Events List</h1>
<ul class="list-group">
  <% @events.each do |event| %>
    <%= link_to(event, class: "list-group-item list-group-item-action") do %>
      <h5 class="list-group-item-heading">
        <%= event.name %>
      </h5>
      <p class="mb-1">
        <%= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}" %>
      </p>
    <% end %>
  <% end %>
</ul>
<%= paginate @events %>